### ISSUE TITLE
Fix: Add tasks

### ISSUE THREAD

**Issue by Gabriel-Sous-a** [mindera-school/MS5-To-Do-List#35]
Add button not working sometimes, id adds to the local storage but not to the html

**Comment by LeoHabs** [comment]
O bug comigo está resolvido. Fiz alguns testes e nunca surgiu

**Comment by LeoHabs** [comment]
Na vdd não é muito relevante porque o método de adicionar tasks vai levar um refactor visto que agora há um design novo e mais o campo da descrição
