### ISSUE TITLE
Create Login Design

### ISSUE THREAD

**Issue by Gabriel-Sous-a** [mindera-school/MS5-To-Do-List#49]

**Comment by LeoHabs** [comment]
Existe uma questão a falar. No design há um link para recuperação de password. É bem pensado mas não se esqueçam que é mais uma pagina e toda mais uma feature para o FE e BE. Na minha opinião é um nice to have, mas de momento não entrava nas contas. Peço que me respondam a isto asap para eu poder corrigir ou não na sidebar que acabei hoje
